# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install vs
        run: |
          choco install microsoft-build-tools --version 12.0.21005.20140416 --force
      
      - name: Git clone
        run: git clone https://github.com/HotswapProjects/openjdk-jdk8u-dcevm.git --branch dcevm8u282b08 --depth 1 --single-branch openjdk-jdk8u-dcevm
        
       #   repository: HotswapProjects/openjdk-jdk8u-dcevm
       #   ref: dcevm8u202b08
       #   path: openjdk-jdk8u-dcevm

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: tree

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            zip
            unzip
            diffutils
            base-devel
      
      - shell: msys2 {0}
        run: |
          cd openjdk-jdk8u-dcevm
          bash ./configure
